name: Deploy to Server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Notify server
        run: |
          curl -X POST https://lostdam.xyz/api/webhook/github \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_SECRET }}" \
            -H "Content-Type: application/json" \
            -d '{}'
